### ISSUE TITLE
mcmetadata not type checked by mypy

### ISSUE THREAD

**Issue by philbudne** [mediacloud/metadata-lib#52]
mypy doesn't see typing info for mcmetadata.
Adding mcmetadata/py.typed seems to cure this
It's mentioned in https://peps.python.org/pep-0561/
but I don't know the right/best way to effect this, or
how this might effect other users of the library!

**Comment by pgulley** [comment]
Added mcmetadata/py.typed and released 0.9.3 to pypi with this change!
