### ISSUE TITLE
Revision Needed: Canonical URL extraction method will break with future versions of trafilatura

### ISSUE THREAD

**Issue by m453h** [mediacloud/metadata-lib#95]
The current approach for extracting canonical URLs using `trafilatura` relies on the behaviour of the version of the library we are currently using (1.8.*). This version automatically extracts metadata from HTML pages regardless of whether the `with_metadata` parameter is specified.

From [trafilatura version 1.11.* ](https://github.com/adbar/trafilatura/releases/tag/v1.11.0) metadata extraction is skipped by default thus would prevent us from automatically extracting canonical URLS. Thus, we need to explore a different approach for the extractor before any future upgrades.

**Comment by philbudne** [comment]
Maybe we should add a comment/warning in requirements.txt about trafilatura versions!

**Comment by m453h** [comment]
Sure I will do the needful!
