### ISSUE TITLE
Enable black formatter in Pre-Commit Hooks

### ISSUE THREAD

**Issue by m453h** [mediacloud/metadata-lib#96]
Upon reviewing the current [pre-commit hooks](https://github.com/mediacloud/metadata-lib/blob/main/.pre-commit-config.yaml) in this repository, it appears that the [Black formatter](https://github.com/psf/black) is not enabled. Can we consider adding it in the future to ensure consistency in the codebase?

**Comment by pgulley** [comment]
Nice job jumping in, thanks!
