### ISSUE TITLE
Add trafilatura version warning to pyproject.yaml?

### ISSUE THREAD

**Issue by philbudne** [mediacloud/metadata-lib#99]
Maybe add the warning about trafilatura versions seen at https://github.com/mediacloud/metadata-lib/blob/1e542fd64344634082689062c2c2d1c427ea404b/mcmetadata/content.py#L199 as a comment at https://github.com/mediacloud/metadata-lib/blob/1e542fd64344634082689062c2c2d1c427ea404b/pyproject.toml#L33 ?

That's what I was thinking when I made the suggestion, but I didn't want to hold up the PR!

**Comment by m453h** [comment]
@philbudne I do agree, since all the dependencies are pinned we can keep the comment here as well for better visibility, I'll submit a PR to update the documentation
